### PR TITLE
Support for crossbuilding docker images and push manifest

### PR DESCRIPTION
**Pull request by mkumatag**
This PR will help building `calico/confd` for all the supported architecture on any architecture(e.g: build arm64, amd64, ppc64le, s390x).

### CODE REVIEW

**Comment by deitch** [comment]
Nice @mkumatag . Thanks for pushing this ahead!

May I make a few comments?

* At the request of @caseydavenport , we have been adding `build` and `image` targets to compile for local architecture and image for local architecture as a standard across all the calico projects. So in this case:

```Makefile
build: bin/confd
# ...
image: container
```

* there is a move towards `Dockerfile.<arch>` instead of `Dockerfile-<arch>`
* we have been moving `Dockerfile` to `Dockerfile.amd64` so it is explicit, and then a symlink `Dockerfile -> Dockerfile.amd64`. Net result is the same, but `amd64` arch becomes explicit
* I recommend having an explicit `bin/confd-$(ARCH)` target for each arch, and then make `bin/confd` default to `bin/confd-$(ARCH)`, like we have done in other projects. See [here](https://github.com/projectcalico/felix/blob/master/Makefile#L247)

Nice work. Now let's get the great Calico team to merge it in.

**Comment by mkumatag** [comment]
@deitch I addressed all of your comments except last one bacuse in lot of places they were using the target name(bin/confd) for generating binary names etc. PTAL latest code. -Thanks

**Comment by deitch** [comment]
Not sure what to say. You did nice work. 

Take a look at the branch I have open [here](https://github.com/deitch/calico-confd/tree/cross-compile).

It is very very similar. Here are the differences:

* I stayed away from manifest-tool. I don't know if you were on the Slack discussion a week or so ago, but @caseydavenport and @fasaxc asked that we keep the PRs smaller and separate.
* Moved `Dockerfile` to an explicit `Dockerfile.amd64` and then symlink `Dockerfile -> Dockerfile.amd64`
* Added the `help` target
* Added the default `bin/confd` as a hardline to `bin/confd-amd64` as a default, per a request in Slack from @fasaxc 
* Added default container images (without `ARCH`) for `amd64`, just because it is a separate PR for manifest

@fasaxc and @caseydavenport haven't quite signed off on the method for manifest tool yet, but they have on the cross-compiling (which already is merged in to Typha and Felix).

Thoughts?

**Comment by mkumatag** [comment]
I'm okay with either of the approach ultimately we are looking at cross-building and push the manifest image.

Please feel free to create a PR with the manifest-tool in it.

To avoid this confusion, lemme create one issue with all the projects we need to work on and progress so far.

**Comment by deitch** [comment]
> Please feel free to create a PR with the manifest-tool in it.

No, opposite. I have a branch _without_ the manifest-tool. Everything _but_ that.

> To avoid this confusion, lemme create one issue with all the projects we need to work on and progress so far

That would be appreciated. :-)

**Comment by mkumatag** [comment]
closing this PR in the favor of #106, will open a separate PR for just pushing manifest later

**Pull request closed without merging**
