### PR TITLE
Fix IPv6 passive calculation

### PR DESCRIPTION
**Pull request by fasaxc**
- Fixes https://github.com/projectcalico/calico/issues/2458 by comparing IPv6 addresses of both nodes instead of IPv4 and IPv6.
- Adds tests that cover IPv6 mesh.

### CODE REVIEW

**Comment by kahou82** [comment]
@fasaxc thanks for fixing it. I am using 3.5.3. Which tagged version should I pull?

**Comment by caseydavenport** [comment]
@kahou82 this will be in v3.5.4, which hasn't been released yet but should be by early next week.

**Comment by kahou82** [comment]
@caseydavenport is 3.6/3.5.4 out yet? If not, can you point me to the dev images I can use?

**Comment by caseydavenport** [comment]
@kahou82 those came out earlier today - v3.5.4 and v3.6.1

**Pull request merged**
