### PR TITLE
New feature for maintaining original next hop on specific bgppeer

### LINKED ISSUE #308: Keep next hop in BGP advertisement.
Hello,

After [this request](https://github.com/projectcalico/confd/pull/257#issuecomment-571279379) I'm opening a new issue.

we are running Project Calico 3.8.1 as SDN for our on-premise k8s clusters. Our network looks as follows:

We host worker nodes in different edge zones (fire compartments). The edge zones are interconnected by an L3VPN.
All worker nodes run a single calico-node pod which is deployed as a daemon set.
We have two calico-node pods per edge zone which are configured to serve as route reflectors (RRs).
Each RR maintains an eBGP session with the EoR switch in the same edge zone.
All EoR switches and the distribution switch peer with each other in the L3VPN (iBGP full mesh).
All RRs are peering with each other in the same edge zones as iBGP full mesh. Each calico-node peers with all RRs in the same edge zone (iBGP).
Our ToR switches are plain L2 switches, so we are not able to use them as RRs inline to the traffic path.
Because we are using eBGP between the RRs and the EoR switches, the default behavior looks like "next hop self" is set.
In this case traffic from the EoRs towards the workloads inside an edge zone would be routed through the route reflectors.
Instead, we want the traffic to be routed directly towards the worker nodes.
That's why we set the option "next hop keep" in the bird configuration and deployed a custom calico-node image.

Would it be possible to have this option configurable e.g. via an environment variable?
Would it be possible to configure "next hop keep" as a default for each and every calico-node, because in our opinion it never makes sense to route the traffic through a calico-node configured as RR?

next_hop

### PR DESCRIPTION
**Pull request by gunboe**
An option to keep the original nexthop field when routes are sent to a BGP Peer. Setting "true" configures the selected BGP Peers node to use the "next hop keep;" instead of "next hop self;"(default) in the specific branch of the Node on "bird.cfg". Thus routes will be send to the external Router maintaining the BGP Original Next Hop. So traffic incoming from external Router can be forwarded directly to the Nodes, without through the Route Reflector.

However require PR (https://github.com/projectcalico/libcalico-go/pull/1266)

This fix #308

### CODE REVIEW

**Comment by fasaxc** [comment]
I've merged the libcalico-go changes.  Please update go.mod to point to the latest master commit of libcalico-go, then run make build and commit the go.mod and go.sum

**Comment by gunboe** [comment]
Hi @fasaxc , its done. Thank you

**Comment by fasaxc** [comment]
Code looks OK to me now but I think we need a test to verify it. Please can you add one: https://github.com/projectcalico/confd/tree/master/tests

**Comment by gunboe** [comment]
Hi again @fasaxc,
 
I'm trying to add a new test, but is failed when I run `make test`:
```
...
Preparing Calico data for next test
Successfully deleted 4 resource(s)
Populating calico with test data using calicoctl:  explicit_peering/keepnexthop
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: keepOriginalNextHop

=== confd single-shot log:
2020-07-24 22:03:38.758 [INFO][849] confd/config.go 60: Found FELIX_TYPHAADDR=127.0.0.1:5473
...
```
I suppose that Kubernetes CRD is not accessible from this point.

Is there some trick to workaround that? Or am I so out? Thank you for any help.

I've created a new directory `./confd/tests/mock_data/calicoctl/explicit_peering/keepnexthop` with manisfest `input.yaml` and inserted it in `test_suite_common.sh`.

```
kind: BGPConfiguration
apiVersion: projectcalico.org/v3
metadata:
  name: default
spec:
  asNumber: 64532
  nodeToNodeMeshEnabled: false

---

# This BGPPeer peers the RR node (kube-master) with an explicit
# external peer and maintain orignal next hop.
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: bgppeer-1
spec:
  peerIP: 172.19.4.87
  asNumber: 64533
  nodeSelector: has(routeReflector)
  keepOriginalNextHop: true

---

# This BGPPeer peers the RR node (kube-master) with an explicit
# external v6 peer and maintain orignal next hop.
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: bgppeer-v6
spec:
  peerIP: "[ac13::57]:50"
  asNumber: 64533
  nodeSelector: has(routeReflector)
  keepOriginalNextHop: true

---

# This BGPPeer peers the RR node (kube-master) with the other
# non-RR nodes in the cluster (kube-node-1, kube-node-2).
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: bgppeer-other-nodes
spec:
  nodeSelector: all()
  peerSelector: has(routeReflector)

---

kind: IPPool
apiVersion: projectcalico.org/v3
metadata:
  name: ippool-1
spec:
  cidr: 192.168.0.0/16
  ipipMode: Always
  natOutgoing: true

---

kind: Node
apiVersion: projectcalico.org/v3
metadata:
  name: kube-master
  labels:
    routeReflector: true
spec:
  bgp:
    ipv4Address: 10.192.0.2/16
    ipv6Address: fe0a::2/96
    routeReflectorClusterID: 10.0.0.1

---

kind: Node
apiVersion: projectcalico.org/v3
metadata:
  name: kube-node-1
spec:
  bgp:
    ipv4Address: 10.192.0.3/16

---

kind: Node
apiVersion: projectcalico.org/v3
metadata:
  name: kube-node-2
spec:
  bgp:
    ipv4Address: 10.192.0.4/16
```

**Comment by gunboe** [comment]
Or calico/ctl is out of date!

**Comment by gunboe** [comment]
> Or `calico/ctl` or `go-build` is out of date!?

Eureka!  `calicoctl` does not yet support the new feature `keepOriginalNextHop` from libcalico-go. 
And so I have one question: Must I create the expected bird files in `compiled_templates/explicit_peering/keepnexthop/`?

**Comment by neiljerram** [comment]
@gunboe To answer your other questions...

> calicoctl does not yet support the new feature keepOriginalNextHop from libcalico-go. Is it a problem that I have resolv in my enviroment or is it a simple "magic" merge in calicoctl repository?

Since the libcalico-go PR was merged 8 days ago, the calico/ctl:master image should have automatically updated by now.  Are you still seeing a problem here?  You might need to clean your repo so that it does a fresh calicoctl download.

> Must I create the expected bird files in compiled_templates/explicit_peering/keepnexthop/ or is ti not necessary?

Yes please.  I'm afraid the test suite in this repo is very low tech!

**Comment by gunboe** [comment]
> @gunboe Thanks for this work. There's just a bit of subtlety that we should check on. Firstly, the `(ne $data.as_num $node_as_num)` condition means that `KeepOriginalNextHop` is only effective for eBGP peerings. Secondly, the fact that the code does not consider setting `bgpPeer.keepNextHop` in `nodeAsBGPPeers` means that the `next hop keep;` setting could be asymmetric when a BGPPeer generates peering in both directions between two Calico nodes with different AS numbers.
> 
> I guess the primary use case for you is eBGP peering from a Calico node to a non-Calico BGP speaker, and for that case the existing code is fine. I'm a bit worried though about leaving the asymmetry mentioned in the "Secondly ..." sentence above. WDYT?

Hi @neiljerram, about your worried though, If I really understood it, I think that the `next hop <keep|self>;` is a asynchronous mechanism  by default. I mean, between 2 eBGP peers (even 2 Calicos Nodes), both or only one can use this flag or not, depends on the direction do you want to exchange the routes. But maybe I've not well visualized your though.

And indeed, I have set `(ne $data.as_num $node_as_num)` condition to ensure that only eBGP peerings would be used, not between internal Calico routers, since the Router Reflector already do this well within iBGP. 

That's what I think, does make sense? I'm a nubie here... I'll apreciate so much learn more with all of you.

> 
> Do you also have a docs PR in progress? It would be good to make sure that the docs are precise on these points.

No, I didn't, and my English is awful, but I can try out. But where could I beginning ? What repo must I edit?

**Comment by gunboe** [comment]
> Since the libcalico-go PR was merged 8 days ago, the calico/ctl:master image should have automatically updated by now. Are you still seeing a problem here? You might need to clean your repo so that it does a fresh calicoctl download.

So I will test again.

> Yes please. I'm afraid the test suite in this repo is very low tech!

No problem, I will do that after all. Thank you for your time @neiljerram !

**Comment by neiljerram** [comment]
@gunboe Thanks for your thoughts.  You're right that the "next hop keep" setting could correctly be asymmetric, in general.  The slight theoretical problem for us, though, is: suppose we use a BGPPeer to configure peering between two Calico nodes with different AS numbers, and we want "next hop keep" on both sides?  I'm not sure if many Calico users have used it in practice, but the "AS per compute server" model that we describe at https://docs.projectcalico.org/reference/architecture/design/l3-interconnect-fabric#the-as-per-compute-server-model would involve that kind of peering.

However, on reflection I think your current proposed code is still good enough, because it's quite easy to avoid relying on the implicit reverse peering for a BGPPeer, by configuring another explicit BGPPeer for the reverse direction.  For example, if you had

```
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: bgppeer-1
spec:
  nodeSelector: node-name == 'a'
  peerSelector: node-name == 'b'
  keepOriginalNextHop: true
```

then you could also configure

```
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: bgppeer-1-reverse
spec:
  nodeSelector: node-name == 'b'
  peerSelector: node-name == 'a'
  keepOriginalNextHop: true
```

and in common cases a single BGPPeer can generate peerings in all directions without any implicit reverse logic, e.g.

```
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: bgppeer-1-all
spec:
  nodeSelector: "all()"
  peerSelector: "all()"
  keepOriginalNextHop: true
```

So I think you just need to complete the testing in this repo, and then we'll be good to go.

For the docs, the repo is https://github.com/projectcalico/calico/, and the specific page you need to update is https://github.com/projectcalico/calico/blob/master/reference/resources/bgppeer.md.

**Comment by gunboe** [comment]
@neiljerram Tests files were made and running fine. Could you please make a revision here?

And docs are in these PR: https://github.com/projectcalico/calico/pull/3867.

If there is more to do, am I happy to do it!!

**Comment by neiljerram** [comment]
@gunboe Many thanks, the actual changes are good to go now.  But unfortunately GitHub is a bit confused about them, showing more changes than there really are, and showing a CLA error for "Semaphore Automatic Update".  I think it's something to do with your merge commit.

To fix those, please could you `git rebase` onto the current master, and then force push?  Then I think I'll be able to merge.

**Comment by neiljerram** [comment]
Thanks @gunboe for the rebase!

**Comment by neiljerram** [comment]
Hi @gunboe - a user has just pointed out that we only did this in the BIRD and BIRD6 templates for node-specific peerings (i.e. with a `Node` or `NodeSelector` field) and not for global peerings (i.e. without those fields).  Was that intentional?

**Comment by neiljerram** [comment]
@gunboe FYI: https://github.com/projectcalico/confd/pull/358

**Pull request merged**
