### PR TITLE
Add configurable BGP graceful restart timer

### PR DESCRIPTION
**Pull request by coutinhop**
Add BIRD BGP graceful restart timer configuration when BGPPeer.MaxRestartTime is set

### CODE REVIEW

**Review by mgleung — APPROVED** [review]
LGTM

**Comment by neiljerram** [comment]
@coutinhop We should have some tests for the new field and code.  Please could you add those?

**Comment by coutinhop** [comment]
@neiljerram thanks for catching this! Seems like the testing is in libcalico-go, I was doing some changes manually updating the api pin, but then ended up dropping everything when it was automatically updated. I just put out a PR with the testing (https://github.com/projectcalico/libcalico-go/pull/1445).

**Comment by neiljerram** [comment]
@coutinhop Thanks, testing in libcalico-go is great, but there should be a test in confd too, to check that configuring a BGPPeer with a maxRestartTime value results in a corresponding `graceful restart time ...` line in the BIRD config.  Look for `keepOriginalNextHop` to find tests with a similar structure (i.e. BGPPeer -> BIRD config).

**Comment by coutinhop** [comment]
I put out https://github.com/projectcalico/confd/pull/545 with the missing testing

**Pull request merged**
