### PR TITLE
Fix typo in cmd for reloading bird6

### LINKED ISSUE #286: bird6 aggregation confd reload_cmd is wrong
Looks like it send a SIGHUP to bird, not bird6:

https://github.com/projectcalico/confd/blob/master/etc/calico/confd/conf.d/bird6_aggr.toml#L7

### PR DESCRIPTION
**Pull request by neiljerram**
Fixes #286

### CODE REVIEW

**Comment by neiljerram** [comment]
@tmjd I've been mulling about various possible ways that I **could** test this, but I can't think of anything simple enough to be worth it.

For example, I could make the current test run executables (in the same test container environment) named bird and bird6, and somehow arrange for them to record what signals they receive - perhaps by running something like `strace -o strace.txt nohup sleep 3600`.  But it seems anything as complex as that will cause us trouble down the line, which probably is not justifiable for this typo fix.

WDYT?

**Comment by tmjd** [comment]
Without this fix the bird6 never would have been restarted with config changes, could you test with the current release and making a change (that should cause bird6 to restart) does not restart it but then with the new version that the same kind of change does cause the process to restart?
From a quick google, it looks like a command like `ps -eo pid,lstart,cmd` should show the start time.

**Comment by tmjd** [comment]
I guess if you're automating that it should be enough that checking the start time of the bird6 process would be enough to see that it was restarted. Get start time, make a change, check that start time is different.

**Comment by neiljerram** [comment]
@tmjd Yes, bird6 would have been restarted (or, in fact, reconfigured in response to SIGHUP) because confd generates 3 config files for bird6, and 2 of those have the correct `reload_cmd = pkill -HUP bird6`.  The bug here would only be observable, transiently, for a change in a specific area of the v1 data model (corresponding to IPv6 IP blocks), and would be cleared by changes in other parts of the data model.

**Comment by neiljerram** [comment]
About looking at the bird6 start time: the problem is that the existing confd tests don't even run bird at all; they simply check the generated config files. So there is no process whose start time we can check.

Also, I'm pretty sure that the SIGHUP does not cause bird to restart. I believe bird handles that signal as an instruction to reread its config.

**Pull request merged**
